### ISSUE TITLE
No matter the output value, it outputs json

### ISSUE THREAD

**Issue by NuxRo** [apache/cloudstack-cloudmonkey#15]
No matter what "set output" I set, it keeps outputing json. 
In particular I expected "text" output to be the old default without the colours, it's kind of handy.

**Comment by swill** [comment]
I believe that Rohit mentioned that he was standardizing on JSON as the output format in order to simplify the implementation. 

@NuxRo, I am guessing that it is for readability that you like the `text` based output?  Would the output from something like ZeroLog (https://github.com/rs/zerolog) fit what you are trying to solve for?  I am not sure if Rohit has any plans to support the `text` format again, but it would be good to better understand what the use case is at this point if he does plan to spend some time to add it in the future.

**Comment by NuxRo** [comment]
Ah, okay, well then, if it's a feature than I'll back off. I misunderstood what will and will not be still available, thought only the colours would go away.

I guess output can be piped to other tools to make it more human readable. I don't have a problem in particular I am trying to solve with this, it was just easier on my eyes. :)

**Comment by swill** [comment]
I would recommend that we get an idea from @rhtyd about what he thinks makes sense to support going forward.  There are ways to potentially pip to another tool for human readability if that is the core concern, but I think others will also be interested in this, so having the issue here to help document and clarify is useful.
