### ISSUE TITLE
Golang rationale

### ISSUE THREAD

**Issue by bwsw** [apache/cloudstack-cloudmonkey#33]
@PaulAngus @DaanHoogland @GabrielBrascher @mike-tutkowski @rhtyd @rafaelweingartner 

It's a calling for a discussion. Is it worth going from Python to Golang? Recently I packed python-based cloudmonkey with pyinstaller into a single executable and it can be deployed as well as a golang binary. I mean that the CloudStack community has some python engineers and it's easier to support the only platform rather than two at once.

I just think that the CloudStack community is not so broad to involve new technologies into the dev stack.

Check: https://www.pyinstaller.org/

**Comment by kiwiflyer** [comment]
To play devils advocate here, we (ENA) have far more Go coders than python experts.

**Comment by rhtyd** [comment]
Python based cloudmonkey will continue to exist, but deprecated over time. May be supported till python 2.7 is supported on a platform. I did discuss about this effort a very long time ago on dev ML and did not receive any negative feedback, since then I've actually rewritten cmk in Go twice. 

Let me share my reasons of rewriting cloudmonkey in go:
- missing support for python 2.7 runtime on older distros such as centos6/el6, difficulty in installation esp for windows users
- python 2 vs 3 issues, before going to rewrite I tried to make the same code compatible with both py2/3 runtime and it turned out to be an ugly exercise
- biggest reason was due to maintenance problem around installation and usage on different platforms
- `go` is a very small language, easy/fast to learn (note: I'm largely a Python programmer, but could pickup quickly, I think others may quickly learn too)
- the rewrite is generally 5-20x faster, easy to build, install and ship as a single binary for various platforms, even works on windows
- cloudmonkey is a very small tool, rewriting it was justifiable; go-based cmk aims to be largely backward compatible for users and does not aim to bring major features

Most new infra opensource projects such as docker, k8s, hashicorp tools, few dbs, etc are all go-based, with the compatibility gurantee from the golang team for 1.x, I see a long term future and also for cmk release and maintenance.

I'm open to a healthy discussion.

**Comment by bwsw** [comment]
@rhtyd well, I understand that. Just wanted to point that `pyinstaller` allows packing python into SFX which can be executed even in outdated OSes, so it's possible to rewrite to python3 as well and run SFX to execute everywhere.

**Comment by bwsw** [comment]
Ok, I get the point. Then, at least the documentation must be changed as well here:
https://cloudstack.apache.org/downloads.html
because, I suppose the current adoption of a new version is almost zero. E.g. I've known then there is some Cloudmonkey in Golang, but documentation states to use pip.

**Comment by rhtyd** [comment]
You're missing the point, there is no official go based release yet. We're yet to work on it and we'll update the website once there is an official release.

**Comment by bwsw** [comment]
@rhtyd 
OK, I finally have got the point. Hope the new tool will get enough adoption soon.
